services:
  db:
    container_name: postgres
    image: postgres:15.1
    environment:
      POSTGRES_USER: janex
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432" #inside localhost(pc):inside container
    networks:
      - db
    restart: unless-stopped
  jpetras-api:
    container_name: jpetras-api
    image: jpetras/jpetras-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: