name: CD - Deploy Backend

on:
  workflow_dispatch:
  # On event push to main branch
  push:
    branches:
      - main
    paths:
      - backend/**

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_USER: janex
          POSTGRES_PASSWORD: password
          POSTGRES_DB: customer
        ports:
          - 5332:5432 # host:container
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Send Slack Message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {"text":"Deployment started :progress_bar: :fingerscrossed:"}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Checkout entire code into the runner
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Generate tag for docker image and send it to $GITHUB_OUTPUT
      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Send Slack Message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {"text":":maven: Building with Maven"}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Build Package Push with Maven
        run: mvn -ntp -B verify -Ddocker.image.tag=${{ steps.build-number.outputs.BUILD_NUMBER }} jib:build
      - name: Send Slack Message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {"text":":docker: Image tag: ${{ steps.build-number.outputs.BUILD_NUMBER }} pushed to ${{ secrets.DOCKER_HUB_REPOSITORY_URL }}"}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Update Dockerrun.aws.json api image tag with new build number
        run: |
          echo "Dockerrun.aws.json before updating tag"
          cat ../Dockerrun.aws.json
          sed -i -E 's_(jpetras/jpetras-api:)([^"]*)_\1'${{ steps.build-number.outputs.BUILD_NUMBER }}'_' ../Dockerrun.aws.json
          echo "Dockerrun.aws.json after updating tag"
          cat ../Dockerrun.aws.json
      - name: Send Slack Message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {"text":":aws: Starting deployment to Elastic Beanstalk"}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Deploy to Elastic Bwanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: ${{ github.SHA }}
          region: ${{ secrets.EB_REGION }}
          # Full path is needed
          deployment_package: Dockerrun.aws.json
      - name: Send Slack Message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {"text":":githubloading: Committing to repository: ${{ secrets.GIT_SPRING_BOOT_FULLSTACK_REPOSITORY_URL }}"}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Commit and push Dockerrun.aws.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ../Dockerrun.aws.json
          git commit -m "Update Dockerrun.aws.json docker image with new tag ${{ steps.build-number.outputs.BUILD_NUMBER }}"
          git push
      - name: Send Slack Message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {"text":"Deployment and commit completed :github_check_mark: :party_blob: :partyblob: - ${{ secrets.EB_ENVIRONMENT_URL }}"}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Send Slack Message
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          if: ${{ job.status == 'Job status failure' }}
          payload: |
            {"text":"Job status ${{ job.status }} :error_: :terror:"}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Send Slack Message
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          if: ${{ job.status != 'Job status failure' }}
          payload: |
            {"text":"Job status ${{ job.status }} :celebrate_party: :done:"}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}